In [1]:
%pip install -r requirements.txt


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [29]:
import numpy as np

arr = np.zeros((8,8))
for i in range(8):
  for j in range(8):
    if (i-j) % 2 == 0:
      arr[i][j] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [30]:
arr = np.array([np.arange(0, 5, 1) for _ in range(5)])

arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [31]:
arr = np.random.random((3,3,3))

arr

array([[[0.74641303, 0.59847125, 0.8593108 ],
        [0.13991917, 0.37655154, 0.81065371],
        [0.7103047 , 0.02293601, 0.76753962]],

       [[0.79430881, 0.99445863, 0.48585781],
        [0.39111021, 0.69903753, 0.16864898],
        [0.01467823, 0.18414896, 0.67354285]],

       [[0.79400333, 0.27102706, 0.39045736],
        [0.79354917, 0.93267794, 0.19257448],
        [0.14343485, 0.96755819, 0.98429748]]])

In [32]:
arr = np.zeros((5,5))
for i in range(5):
  arr[0][i] = 1
  arr[4][i] = 1
  arr[i][0] = 1
  arr[i][4] = 1

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
arr = np.random.random(10)
arr[::-1].sort()

arr

array([0.94886642, 0.92967673, 0.73741657, 0.7150817 , 0.5433762 ,
       0.24725678, 0.16721034, 0.14996405, 0.11383825, 0.07040988])

In [34]:
arr = np.zeros((6,6,6))

print(f"Shape: {arr.shape}, Size: {arr.size}, Dim: {len(arr.shape)}")

Shape: (6, 6, 6), Size: 216, Dim: 3


In [35]:
import pandas as pd

a = {"x": 4, "y": 2, "z": 5}
b = {"x": -2, "y": 3, "z": -1}
A = pd.Series(data=a, index=["x", "y", "z"])
B = pd.Series(data=b, index=["x", "y", "z"])

dist = ((B.x-A.x)**2 + (B.y-A.y)**2 + (B.y-A.y)**2)**0.5
dist

np.float64(6.164414002968976)

In [36]:
df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/cpu_act.csv")
df

1   2     3    4    5      6      7       8       9     10  ...  \
0      6   2  1036  103  114   1.00   1.00  172076  355965   0.00  ...   
1      1   0  2165  205  101   0.40   1.20   43107   44139   4.80  ...   
2     62  77  3806  258  166   1.40   1.40  492142  268706   4.80  ...   
3      5   0  4721  256  177   0.99   2.58  524787  174964  14.51  ...   
4     42  55  3949  249  244   2.60   4.60  197289  529200   4.20  ...   
...   ..  ..   ...  ...  ...    ...    ...     ...     ...    ...  ...   
8187  74  49  2688  176  103  11.00  32.20   57714   38484   0.80  ...   
8188  29  40  1906  118   90   0.80   2.00    8175   27313   0.00  ...   
8189   3   0   926   90   67   0.60   1.00    5411   19322   0.00  ...   
8190   4   0   418   30   29   0.80   1.00    3959   10679   0.00  ...   
8191   5   0  1888  248  215   6.20   1.80  216420   39346   0.00  ...   

          13    14     15     16      17      18   19    20       21  22  
0       0.00  0.00   2.00   4.00   73.60   89.00  2.0  6527  1851864  90  
1     181.40  0.20  85.40  88.20   19.40  161.80  3.0   130  1131931  88  
2      79.20  2.20   7.60  12.20   68.00  218.80  5.2   256  1314590  85  
3     189.86  1.99   4.17  24.85   95.63  248.91  1.0   233   972606  81  
4       0.00  1.40   1.80   2.20  219.60  297.20  3.4   331  1013805  79  
...      ...   ...    ...    ...     ...     ...  ...   ...      ...  ..  
8187    0.00  0.00   0.80   0.80  343.20  649.40  7.0   314  1096333  69  
8188    0.00  0.00   0.80   0.80   56.20   78.60  3.6   166  1107088  88  
8189    0.00  0.40   0.40   0.40   53.40  154.00  1.0  1177  1020400  92  
8190    0.00  0.00   0.20   0.20   61.00   73.20  2.4  6355  1702592  96  
8191    0.00  0.00   7.40  14.80  296.60  420.20  4.6  1628  1757696  80  

[8192 rows x 22 columns]

In [37]:
df.head(2)

1  2     3    4    5    6    7       8       9   10  ...     13   14    15  \
0  6  2  1036  103  114  1.0  1.0  172076  355965  0.0  ...    0.0  0.0   2.0   
1  1  0  2165  205  101  0.4  1.2   43107   44139  4.8  ...  181.4  0.2  85.4   

     16    17     18   19    20       21  22  
0   4.0  73.6   89.0  2.0  6527  1851864  90  
1  88.2  19.4  161.8  3.0   130  1131931  88  

[2 rows x 22 columns]

In [38]:
df.tail(2)

1  2     3    4    5    6    7       8      9   10  ...   13   14   15  \
8190  4  0   418   30   29  0.8  1.0    3959  10679  0.0  ...  0.0  0.0  0.2   
8191  5  0  1888  248  215  6.2  1.8  216420  39346  0.0  ...  0.0  0.0  7.4   

        16     17     18   19    20       21  22  
8190   0.2   61.0   73.2  2.4  6355  1702592  96  
8191  14.8  296.6  420.2  4.6  1628  1757696  80  

[2 rows x 22 columns]

In [39]:
df.shape

(8192, 22)

In [40]:
df.describe()

1            2             3            4            5  \
count  8192.000000  8192.000000   8192.000000  8192.000000  8192.000000   
mean     19.559692    13.106201   2306.318237   210.479980   150.058228   
std      53.353799    29.891726   1633.617322   198.980146   160.478980   
min       0.000000     0.000000    109.000000     6.000000     7.000000   
25%       2.000000     0.000000   1012.000000    86.000000    63.000000   
50%       7.000000     1.000000   2051.500000   166.000000   117.000000   
75%      20.000000    10.000000   3317.250000   279.000000   185.000000   
max    1845.000000   575.000000  12493.000000  5318.000000  5456.000000   

                 6            7             8             9           10  ...  \
count  8192.000000  8192.000000  8.192000e+03  8.192000e+03  8192.000000  ...   
mean      1.884554     2.791998  1.970137e+05  9.589829e+04     2.285317  ...   
std       2.479493     5.212456  2.394808e+05  1.407569e+05     5.307038  ...   
min       0.000000     0.000000  2.780000e+02  1.498000e+03     0.000000  ...   
25%       0.400000     0.200000  3.386425e+04  2.293550e+04     0.000000  ...   
50%       0.800000     1.200000  1.247795e+05  4.662000e+04     0.000000  ...   
75%       2.200000     2.800000  2.676692e+05  1.061480e+05     2.400000  ...   
max      20.120000    59.560000  2.526649e+06  1.801623e+06    81.440000  ...   

                13           14           15           16           17  \
count  8192.000000  8192.000000  8192.000000  8192.000000  8192.000000   
mean     21.526849     1.127505     8.277960    12.388586   109.793799   
std      71.141340     5.708347    13.874978    22.281318   114.419221   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.600000     0.600000    25.000000   
50%       0.000000     0.000000     2.800000     3.800000    63.800000   
75%       0.000000     0.600000     9.765000    13.800000   159.600000   
max    1237.000000   211.580000   141.200000   292.610000   899.800000   

                18           19            20            21           22  
count  8192.000000  8192.000000   8192.000000  8.192000e+03  8192.000000  
mean    185.315796    19.630676   1763.456299  1.328126e+06    83.968872  
std     191.000603   125.742085   2482.104511  4.220194e+05    18.401905  
min       0.200000     1.000000     55.000000  2.000000e+00     0.000000  
25%      45.400000     1.200000    231.000000  1.042624e+06    81.000000  
50%     120.400000     2.000000    579.000000  1.289290e+06    89.000000  
75%     251.800000     3.000000   2002.250000  1.730380e+06    94.000000  
max    1365.000000  2823.000000  12027.000000  2.243187e+06    99.000000  

[8 rows x 22 columns]

In [41]:
df.loc[2:5]

1   2     3    4    5     6     7       8       9     10  ...      13  \
2  62  77  3806  258  166  1.40  1.40  492142  268706   4.80  ...   79.20   
3   5   0  4721  256  177  0.99  2.58  524787  174964  14.51  ...  189.86   
4  42  55  3949  249  244  2.60  4.60  197289  529200   4.20  ...    0.00   
5   5   1  1692  132   87  0.40  1.80  220194  107031   0.00  ...    0.00   

     14    15     16      17      18   19    20       21  22  
2  2.20  7.60  12.20   68.00  218.80  5.2   256  1314590  85  
3  1.99  4.17  24.85   95.63  248.91  1.0   233   972606  81  
4  1.40  1.80   2.20  219.60  297.20  3.4   331  1013805  79  
5  0.00  3.81   4.01   23.65   42.08  2.2  2291  1010703  92  

[4 rows x 22 columns]

In [42]:
df.iloc[2:5]

1   2     3    4    5     6     7       8       9     10  ...      13  \
2  62  77  3806  258  166  1.40  1.40  492142  268706   4.80  ...   79.20   
3   5   0  4721  256  177  0.99  2.58  524787  174964  14.51  ...  189.86   
4  42  55  3949  249  244  2.60  4.60  197289  529200   4.20  ...    0.00   

     14    15     16      17      18   19   20       21  22  
2  2.20  7.60  12.20   68.00  218.80  5.2  256  1314590  85  
3  1.99  4.17  24.85   95.63  248.91  1.0  233   972606  81  
4  1.40  1.80   2.20  219.60  297.20  3.4  331  1013805  79  

[3 rows x 22 columns]

In [43]:
df[df["1"] < 5]

1  2     3    4    5     6    7       8       9   10  ...     13   14  \
1     1  0  2165  205  101  0.40  1.2   43107   44139  4.8  ...  181.4  0.2   
6     3  0   635   65   47  3.00  3.0   87465   40740  8.6  ...    0.0  0.0   
9     1  0  3322  271  170  1.00  3.2  399277  128680  0.0  ...    0.0  0.0   
12    2  1  5402  406  274  0.20  0.2   22609  155154  2.2  ...    8.0  0.4   
21    4  0  1969  209  200  2.40  0.8  131479   48942  0.0  ...    0.0  0.2   
...  .. ..   ...  ...  ...   ...  ...     ...     ...  ...  ...    ...  ...   
8182  3  0  3580  278  230  3.19  1.0  292840   55884  0.0  ...    0.0  0.4   
8183  0  0   160   13   18  0.20  0.2    2085    4636  0.0  ...    0.0  0.0   
8184  2  1   637  102   95  0.40  0.2   37606   49019  0.0  ...    0.0  0.2   
8189  3  0   926   90   67  0.60  1.0    5411   19322  0.0  ...    0.0  0.4   
8190  4  0   418   30   29  0.80  1.0    3959   10679  0.0  ...    0.0  0.0   

         15     16      17      18   19    20       21  22  
1     85.40  88.20   19.40  161.80  3.0   130  1131931  88  
6      1.60   2.20  227.60  226.40  1.0   289  1806587  82  
9      6.40   9.20   32.80   93.60  1.0   579  1120168  86  
12     7.40   7.40   33.00   54.20  2.5   152  1015040  84  
21     0.80   1.40  125.05  179.36  1.3  1126  1053153  89  
...     ...    ...     ...     ...  ...   ...      ...  ..  
8182  18.76  23.15  163.07  358.08  4.2  1006  1388792  84  
8183   0.00   0.00   15.60   16.80  1.0  7426  1866406  98  
8184  17.80  17.80   19.20   61.80  1.5   391  1092827  96  
8189   0.40   0.40   53.40  154.00  1.0  1177  1020400  92  
8190   0.20   0.20   61.00   73.20  2.4  6355  1702592  96  

[3404 rows x 22 columns]

In [44]:
import sklearn as sk
from sklearn.preprocessing import MinMaxScaler, StandardScaler

df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
mm_scaler = MinMaxScaler()
z_scaler = StandardScaler()

df[["sepal_length_cm"]] = mm_scaler.fit_transform(df[["sepal_length_cm"]])
df[["sepal_width_cm"]] = z_scaler.fit_transform(df[["sepal_width_cm"]])
df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]